version: '3.8'

services:
    husarnet:
        image: husarnet/husarnet
        restart: unless-stopped
        ipc: shareable
        volumes:
            - /var/lib/husarnet
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        environment:
            - HOSTNAME=listener
            - JOINCODE

    ros2router:
        image: husarnet/ros2router:1.6.0
        network_mode: service:husarnet
        volumes:
            # see filter config at https://github.com/husarnet/husarnet-ros2router
            - ./filter.yaml:/filter.yaml
        restart: unless-stopped
        environment:
            - EXIT_IF_HOST_TABLE_CHANGED=TRUE
            - ROS_LOCALHOST_ONLY=0   # enables ROS2 Router local LAN participant
            - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}

    listener:
        build: 
            context: .
            dockerfile: Dockerfile
        devices:
            - /dev/net/tun
        command: ros2 run demo_nodes_cpp listener
        network_mode: service:husarnet
