version: '3.8'

services:
    
    ros2router:
        build: 
            context: ./ros2router
            dockerfile: Dockerfile
        network_mode: service:husarnet
        volumes:
            # see filter config at https://github.com/husarnet/husarnet-ros2router
            - ./ros2router/filter.yaml:/filter.yaml
        restart: unless-stopped
        environment:
            - EXIT_IF_HOST_TABLE_CHANGED=TRUE
            - ROS_LOCALHOST_ONLY=0   # enables ROS2 Router local LAN participant
            - ROS_DOMAIN_ID
    
    husarnet:
        image: husarnet/husarnet
        restart: unless-stopped
        ipc: shareable
        volumes:
            - /var/lib/husarnet:/var/lib/husarnet
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        environment:
              # set in .env
            - HUSARNET_JOIN_CODE
            - HUSARNET_HOSTNAME
             
    listener:
        build: 
            context: ./listener
            dockerfile: Dockerfile
        environment:
            - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
              # set in .env
            - ROS_DOMAIN_ID
        command: ros2 run demo_nodes_cpp add_two_ints_client
