version: '3.8'

services:

    ros2router:
        build: 
            context: ./ros2router
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes: 
            - ./ros2router/filter.yaml:/filter.yaml
        environment:
            - EXIT_IF_HOST_TABLE_CHANGED=TRUE # if new Husarnet peer is detected restart the DDS Router to apply a new initial-peers config
            - ROS_LOCALHOST_ONLY=0 # enables ROS2 Router local LAN participant
              # set in .env file
            - ROS_DOMAIN_ID
        network_mode: host

    talker:
        build: 
            context: ./talker
            dockerfile: Dockerfile
        devices:
            - /dev/net/tun
        volumes:
            - /var/lib/husarnet:/var/lib/husarnet
        environment:
            - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
              # set in .env file
            - HUSARNET_JOIN_CODE
            - HUSARNET_HOSTNAME
            - ROS_DOMAIN_ID
        cap_add:
            - NET_ADMIN
        network_mode: host
        command: ros2 run demo_nodes_cpp talker
