version: '2.3'

services:

    husarnet:
        image: husarnet/husarnet
        restart: unless-stopped
        ipc: shareable
        #volumes:
        #    - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        environment: 
            - HOSTNAME=listener
            - JOINCODE # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there

    ros2router-2:
        image: husarnet/ros2router:1.6.0
        network_mode: service:husarnet
        restart: unless-stopped
        environment:
            - EXIT_IF_HOST_TABLE_CHANGED=TRUE # if new Husarnet peer is detected restart the DDS Router to apply a new initial-peers config
            - ROS_LOCALHOST_ONLY=0 # enables ROS2 Router local LAN participant
        depends_on:
            - husarnet

    talker:
        image: arm64v8/ros:galactic-ros-base-focal
        #command: ros2 run demo_nodes_cpp talker
        depends_on:
            - husarnet
            - ros2router-2
